In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])
ser1
ser2

X    3
Y    4
dtype: int64

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])
#it labels the concatenated series as an index hierarchy

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])
dframe1


X         Y         Z
0 -0.154642  0.707163 -1.773348
1  0.858227  0.484977 -0.982182
2 -0.991213 -0.039439 -0.627896
3  0.007580 -2.395990  0.996241

In [13]:
dframe2

Y         Q         X
0 -0.789877  2.033824 -0.175810
1 -0.305161 -0.451895 -0.599130
2  1.276653 -0.359818  0.985099

In [14]:
pd.concat([dframe1,dframe2])
#works like a full outer join

Q         X         Y         Z
0       NaN -0.154642  0.707163 -1.773348
1       NaN  0.858227  0.484977 -0.982182
2       NaN -0.991213 -0.039439 -0.627896
3       NaN  0.007580 -2.395990  0.996241
0  2.033824 -0.175810 -0.789877       NaN
1 -0.451895 -0.599130 -0.305161       NaN
2 -0.359818  0.985099  1.276653       NaN

In [16]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.154642  0.707163 -1.773348
1       NaN  0.858227  0.484977 -0.982182
2       NaN -0.991213 -0.039439 -0.627896
3       NaN  0.007580 -2.395990  0.996241
4  2.033824 -0.175810 -0.789877       NaN
5 -0.451895 -0.599130 -0.305161       NaN
6 -0.359818  0.985099  1.276653       NaN

In [ ]:
#there's an Ipython notebook with more documentation on this as well