In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10)

A

array([ 0.26630589, -0.65814864, -1.03979407, -0.30923089, -2.03136023,
        0.31333401, -1.40620541,  0.12684521, -0.18083279,  0.36468792])

In [6]:
B = np.random.randn(10)

B

array([ 1.10170273, -1.04905309,  1.2969831 ,  0.16516318, -0.11662278,
       -0.4096229 ,  0.81976708, -0.48358746, -0.27317163, -0.3939383 ])

In [7]:
#Binary functions
np.add(A,B)

array([ 1.36800862, -1.70720172,  0.25718902, -0.14406771, -2.14798301,
       -0.09628889, -0.58643833, -0.35674224, -0.45400442, -0.02925038])

In [8]:
np.maximum(A,B)

array([ 1.10170273, -0.65814864,  1.2969831 ,  0.16516318, -0.11662278,
        0.31333401,  0.81976708,  0.12684521, -0.18083279,  0.36468792])

In [9]:
import webbrowser
webbrowser.open('http://www.msn.com')

True